### ISSUE TITLE
Centos7+CPU下重新编译各个模块

### ISSUE THREAD

**Issue by w-Bro** [yangjian1218/seetaface6ToPy#3]
@yangjian1218 
已经重新编译了各个模块，最后放到lib中按照你给出的步骤进行编译，也没出现错误
但是执行python  seeta_test.py报错了，请问有遇到这样的问题吗？
```
seetaDevice : SEETA_DEVICE_CPU
deviceId=0
path:/home/python-projects/seetaface6ToPy/seeta/model
ERROR: open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
terminate called after throwing an instance of 'orz::Exception'
  what():  open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
已放弃
```

**Comment by yangjian1218** [comment]
> @yangjian1218 已经重新编译了各个模块，最后放到lib中按照你给出的步骤进行编译，也没出现错误 但是执行python seeta_test.py报错了，请问有遇到这样的问题吗？
> 
> ```
> seetaDevice : SEETA_DEVICE_CPU
> deviceId=0
> path:/home/python-projects/seetaface6ToPy/seeta/model
> ERROR: open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
> terminate called after throwing an instance of 'orz::Exception'
>   what():  open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
> 已放弃
> ```
确定模型放进这个地址了? 这是报错目录错误呀. 如果目录没错,那我也不懂,没遇到过

**Comment by w-Bro** [comment]
> > @yangjian1218 已经重新编译了各个模块，最后放到lib中按照你给出的步骤进行编译，也没出现错误 但是执行python seeta_test.py报错了，请问有遇到这样的问题吗？
> > ```
> > seetaDevice : SEETA_DEVICE_CPU
> > deviceId=0
> > path:/home/python-projects/seetaface6ToPy/seeta/model
> > ERROR: open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
> > terminate called after throwing an instance of 'orz::Exception'
> >   what():  open the model file:/home/python-projects/seetaface6ToPy/seeta/model/face_detector.csta failed!
> > 已放弃
> > ```
> 
> 确定模型放进这个地址了? 这是报错目录错误呀. 如果目录没错,那我也不懂,没遇到过

确实是这个目录，后来重新编译过几次也是这样，放弃了，换了个csta转onnx的做。

**Comment by DiaosWang** [comment]
[model_path = "./seeta/model"](https://github.com/yangjian1218/seetaface6ToPy/blob/7deac4b88cb960cdfac3b929df99476afbd93e70/seeta_test.py#L23)

作者这儿写错了，应该是`model_path = "./seetaface/model"` ，这样就可以打开作者提供的model文件夹，并读取其中的模型文件了。
