### ISSUE TITLE
人脸亮度评估能返回亮度得分吗？

### ISSUE THREAD

**Issue by wennyHou** [yangjian1218/seetaface6ToPy#5]
如题，我看到原始接口除了会返回【LOW、MEDIUM、HIGH】之外，还会返回人脸亮度得分。

**Comment by yangjian1218** [comment]
> 如题，我看到原始接口除了会返回【LOW、MEDIUM、HIGH】之外，还会返回人脸亮度得分。

我提供了方法, 如果需要,你按照我的方法,写对应的代码就好了. 我并没有100%所有的接口都写.
